#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <limits>
#include <vector>
extern "C" {
static constexpr uint32_t SCALE=16,TOT=1u<<SCALE,RANS_L=1u<<23;
static bool norm(const uint64_t*c,uint32_t v,uint32_t*out){uint64_t n=0;uint32_t k=0;for(uint32_t s=0;s<v;s++){n+=c[s];k+=c[s]!=0;}if(!n)return false;struct R{uint32_t s;uint64_t r;};std::vector<R>a;a.reserve(k);int64_t sum=0;for(uint32_t s=0;s<v;s++){if(!c[s]){out[s]=0;continue;}uint64_t p=c[s]*uint64_t(TOT);uint32_t f=p/n;uint64_t r=p%n;if(!f)f=1;out[s]=f;sum+=f;a.push_back({s,r});}std::sort(a.begin(),a.end(),[](R x,R y){return x.r!=y.r?x.r>y.r:x.s<y.s;});if(sum<TOT){uint32_t d=TOT-sum;for(uint32_t j=0;j<d;j++)out[a[j%a.size()].s]++;}else if(sum>TOT){std::sort(a.begin(),a.end(),[](R x,R y){return x.r!=y.r?x.r<y.r:x.s>y.s;});uint32_t d=sum-TOT;for(size_t j=0;d;j=(j+1)%a.size())if(out[a[j].s]>1){out[a[j].s]--;d--;}}return true;}
int p_encode(const uint16_t*v,const uint16_t*cx,uint64_t n,uint32_t nc,uint32_t vocab,uint32_t**freqp,uint8_t**streamp,size_t*sn){try{if(!v||!cx||!n||n>100000000||!nc||!vocab||vocab>TOT||!freqp||!streamp||!sn||(size_t)nc>std::numeric_limits<size_t>::max()/vocab)return 1;*freqp=nullptr;*streamp=nullptr;*sn=0;size_t cells=(size_t)nc*vocab;if(cells>std::numeric_limits<size_t>::max()/sizeof(uint64_t))return 1;std::vector<uint64_t> cnt(cells);for(uint64_t i=0;i<n;i++){if(cx[i]>=nc||v[i]>=vocab)return 2;cnt[(size_t)cx[i]*vocab+v[i]]++;}std::vector<uint32_t> f(cells);for(uint32_t c=0;c<nc;c++)if(!norm(cnt.data()+(size_t)c*vocab,vocab,f.data()+(size_t)c*vocab)&&cnt[(size_t)c*vocab])return 3;std::vector<uint32_t> cum(f.size());for(uint32_t c=0;c<nc;c++){uint32_t z=0;for(uint32_t s=0;s<vocab;s++){cum[(size_t)c*vocab+s]=z;z+=f[(size_t)c*vocab+s];}}uint32_t state=RANS_L;std::vector<uint8_t> ren;for(uint64_t i=n;i-->0;){uint32_t c=cx[i],s=v[i],fr=f[(size_t)c*vocab+s],cu=cum[(size_t)c*vocab+s];uint64_t xmax=((uint64_t)(RANS_L>>SCALE)<<8)*fr;while(state>=xmax){ren.push_back(state&255);state>>=8;}state=((state/fr)<<SCALE)+(state%fr)+cu;}if(ren.size()>std::numeric_limits<size_t>::max()-4)return 4;std::vector<uint8_t> out(4+ren.size());out[0]=state;out[1]=state>>8;out[2]=state>>16;out[3]=state>>24;for(size_t i=0;i<ren.size();i++)out[4+i]=ren[ren.size()-1-i];auto*fp=(uint32_t*)malloc(f.size()*4);auto*sp=(uint8_t*)malloc(out.size());if(!fp||!sp){free(fp);free(sp);return 4;}memcpy(fp,f.data(),f.size()*4);memcpy(sp,out.data(),out.size());*freqp=fp;*streamp=sp;*sn=out.size();return 0;}catch(...){return 5;}}
int p_decode(const uint8_t*st,size_t bytes,uint64_t n,const uint16_t*cx,uint32_t nc,uint32_t v,const uint32_t*f,uint16_t*out){try{if(!st||bytes<4||!cx||!f||!out||!n||n>100000000||!nc||!v||v>TOT||(size_t)nc>std::numeric_limits<size_t>::max()/(v+1))return 1;size_t cells=(size_t)nc*v,prefcells=(size_t)nc*(v+1);if(cells>std::numeric_limits<size_t>::max()/sizeof(uint32_t)||prefcells>std::numeric_limits<size_t>::max()/sizeof(uint32_t))return 1;uint32_t state=st[0]|uint32_t(st[1])<<8|uint32_t(st[2])<<16|uint32_t(st[3])<<24;if(state<RANS_L)return 2;size_t ip=4;std::vector<uint32_t> pref(prefcells);for(uint32_t c=0;c<nc;c++){auto*p=pref.data()+(size_t)c*(v+1);for(uint32_t s=0;s<v;s++){if(f[(size_t)c*v+s]>TOT-p[s])return 3;p[s+1]=p[s]+f[(size_t)c*v+s];}}for(uint64_t i=0;i<n;i++){uint32_t c=cx[i];if(c>=nc)return 5;auto*p=pref.data()+(size_t)c*(v+1);if(p[v]!=TOT)return 4;uint32_t slot=state&(TOT-1);auto it=std::upper_bound(p+1,p+v+1,slot);if(it==p+v+1)return 6;uint32_t s=it-p-1,fr=f[(size_t)c*v+s];if(!fr)return 7;out[i]=s;state=fr*(state>>SCALE)+(slot-p[s]);while(state<RANS_L){if(ip>=bytes)return 8;state=(state<<8)|st[ip++];}}return ip==bytes&&state==RANS_L?0:9;}catch(...){return 10;}}
void p_free(void*p){free(p);}
}
